services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - BackendDb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      command: 
    ports:
      - '8080:3306'
  
volumes: 
  BackendDb:

