services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - BackendDb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AgilestRelationDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '8080:3306'
  mongo:
    image: mongo
    volumes:
      - BackendDb:/var/lib/mongo
    ports:
      - '27017:27017'
volumes: 
  BackendDb:

