name: Go CI

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Install dependencies
      run: |
        go get github.com/go-sql-driver/mysql
        go get go.mongodb.org/mongo-driver
        go mod  tidy
    - name: Build
      run: go build -o main main.go
    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          rm: true
          source: "main/"
          target: "."
    - name: SSH Commands 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          kill -9 $(lsof -t -i:8080)
          ./main


 
