name: GoCI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: SSH Commands 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }} 
        password: ${{ secrets.SSH_KEY }} 
        PORT: 22
        script: |
          cd temporaryBackendSe
          fuser -k 80/tcp
          go build -o main main.go
          ./main&